---
title: "Lab_2_filled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
rm(list = ls()) # clean-up workspace
```

Let's read in the Davis data.

```{r}
davis.data <- read.table("./Davis.txt")
davis.data[12, "height"] <- 166
davis.data[12, "weight"] <- 57

# remove rows with missing data
davis.data <- davis.data[complete.cases(davis.data), ]

# take a look at the data
davis.data
```

-------------------------------------

You need to fill out the following sections for answering the questions.



Construct $X$, $X^TX$, and $Y$.

```{r}
# construct the design matrix
X <- as.matrix(cbind(1, davis.data[, "reportedWeight"]))
# assign names to X column
colnames(X) <- c("intercept", "reportedWeight")

# construct the Gramian matrix
system.time(gramian.mat <- t(X) %*% X)
system.time(gramian.mat <- crossprod(X))
gramian.mat

# calculate the inverse of the Gramian matrix
gramian.mat.inv <- solve(gramian.mat)

# construct the Y matrix
Y <- as.matrix(davis.data[, "weight"])
```

Q1. Now let's calculate the least square estimates

```{r}
# Now calculate the LS estimate
system.time(beta.estimate <- solve(gramian.mat) %*% t(X) %*% Y)
beta.estimate
system.time(beta.estimate <- solve(crossprod(X), crossprod(X, Y)))
beta.estimate
```

Q2. Now calculate the variance-covariance matrix to get the standard error of $\hat{\beta}_1$

```{r}
# calculate sum of squared errors (or residuals)
sse <- crossprod(Y - X %*% beta.estimate)
sse

# calculate mean squared errors
mse <- sse / (dim(X)[1] - 2)
mse

# calculate the variance-covariance matrix for beta hat
sigma.matrix <- as.numeric(mse) * solve(t(X) %*% X)
sigma.matrix

# standard error
sqrt(sigma.matrix[2, 2])
```

Q3. Hypothesis test of $H_0: \beta_1 = 0$

t(0.025, 179) critical value (the design matrix has 181 rows / 181 observations):

```{r}
qt(1.0 - 0.025, 179) #take a look at the documentation of "qt"
# t statistic
beta.estimate[2] / sqrt(sigma.matrix[2, 2])
```

Q4. Mean weight estimate given reportedWeight = 72:

```{r}
a.vector <- c(1, 72)
mean.weight.est <- a.vector %*% beta.estimate
mean.weight.est
```

Q5. standard error:

```{r}
theta.se <- sqrt(crossprod(a.vector, sigma.matrix %*% a.vector))
theta.se
```

Q6. 95% confidence interval:

```{r}
confidence.interval <- as.numeric(mean.weight.est) + c(-1, 1) *  qt(1.0 - 0.025, nrow(X) - 2) * as.numeric(theta.se)
confidence.interval
```


---------------------------------------------------------

Use `lm` to check

```{r}
(lmod <- lm(weight ~ reportedWeight, data = davis.data))
beta.estimate
summary(lmod)

predict(lmod, newdata = data.frame("1" = 1, "reportedWeight" = 72), interval = "confidence")
```

